name: Commit Build and Test

on:
  push:
    branches: [ "*", "!main" ]

permissions:
  contents: read

jobs:
  build_and_test:
    defaults:
      run:
        shell: bash
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Build
      run: |
        ./scripts/build.sh
    - name: Test
      run: |
        ./scripts/test.sh