on:
  push:
    branches: [ "main" ]

permissions: write-all

jobs:
  build_and_test:
    defaults:
      run:
        shell: bash
    runs-on: ubuntu-latest

    env:
      IMAGE_NAME: razmusanderson/baserepo

    steps:
    - uses: actions/checkout@v3
    - name: Login to DockerHub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}

    - uses: actions/setup-node@v3
      with:
        node-version: 16

    - name: Increment Version Number
      run: |
        OLD_VERSION=$(cat VERSION)
        ./scripts/increment-version.sh
        echo Upgrade from v$OLD_VERSION to v$(cat VERSION)

    - name: Setup
      run: |
        ./scripts/setup.sh

    - name: Build
      run: |
        ./scripts/build.sh

    - name: Test
      run: |
        ./scripts/test.sh

    - name: Docker builds
      run: |
        TAG=$(cat VERSION)
        ./scripts/docker-build.sh $IMAGE_NAME $TAG

    - name: Docker push
      run: |
        TAG=$(cat VERSION)
        docker push $IMAGE_NAME:$TAG
        docker push $IMAGE_NAME:latest

    - name: Deploy
      uses: Consensys/kubernetes-action@master
      env:
        KUBE_CONFIG_DATA: ${{ secrets.KUBECONFIG }}
      with:
        args: apply -f deployment.yaml

    - name: Commit Version Increment
      run: |
        git config --local user.email "github-actions[bot]@users.noreply.github.com"
        git config --local user.name "github-actions[bot]"
        git commit -a -m "Upgrade to v$(cat VERSION)"

    - name: Push changes
      uses: ad-m/github-push-action@master
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        branch: main