name: Deploy

on:
  push:
    branches: [ "main" ]

jobs:
  build_and_test:
    defaults:
      run:
        shell: bash
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - uses: undergroundwires/bump-everywhere@master
    - name: Docker build
      run: |
        set TAG=$(git describe --tags)
        docker build . --tag base-repo:$TAG