name: Deploy

on:
  push:
    branches: [ "main" ]

jobs:
  build_and_test:
    defaults:
      run:
        shell: bash
        working-directory: dashboard
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - uses: undergroundwires/bump-everywhere@master